Repository udacity/ML_SageMaker_Studies, pull requests merged in 2021-03, with the labels that each got.

#6 Fixing % not found in matplotlib inline function
  Project_Plagiarism_Detection/1_Data_Exploration.ipynb
Labels: bug

#11 fix: use pd.date_range instead of DatetimeIndex
  Time_Series_Forecasting/Energy_Consumption_Exercise.ipynb
Labels: bug

#13 fix: redundant lines in Plagiarism notebook 3
  Project_Plagiarism_Detection/3_Training_a_Model.ipynb
Labels: improve instruction

#10 docs: replace 2017 with 2007
  Time_Series_Forecasting/Energy_Consumption_Exercise.ipynb
Labels: typo
